/**
 * Multi-Language Configuration
 * Supports: English, Spanish, French, German, Chinese, Japanese, Hindi, Portuguese, Russian, Arabic
 */

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸', nativeName: 'English' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  { code: 'fr', name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  { code: 'de', name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', nativeName: '日本語' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹', nativeName: 'Português' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', nativeName: 'Русский' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية' },
];

export const DEFAULT_LANGUAGE = 'en';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'hi' | 'pt' | 'ru' | 'ar';

export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

export const translations: Translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    income: 'Income',
    expenses: 'Expenses',
    assets: 'Assets',
    bankAccounts: 'Bank Accounts',
    budget: 'Budget',
    analytics: 'Analytics',
    settings: 'Settings',
    logout: 'Logout',

    // Dashboard
    netWorth: 'Net Worth',
    totalIncome: 'Total Income',
    monthlyExpenses: 'Monthly Expenses',
    totalAssets: 'Total Assets',
    allTimeIncome: 'All-time income',
    thisMonth: 'This month',

    // Auth
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    invalidEmail: 'Invalid email format',
    passwordRequired: 'Password is required',
    failedToLogin: 'Failed to login',
    failedToSignup: 'Failed to sign up',

    // Settings
    currentCurrency: 'Current Currency',
    selectCurrency: 'Select Currency',
    currencyBadges: 'Currency Badges',
    allCurrencies: 'All Available Currencies',
    currencyStatistics: 'Currency Statistics',
    totalCurrencies: 'Total Currencies',
    currentLanguage: 'Current Language',
    selectLanguage: 'Select Language',
    yourActiveLanguage: 'Your active language settings',
    allLanguages: 'All Supported Languages',
    languageStatistics: 'Language Statistics',
    totalLanguages: 'Total Languages',
    symbol: 'Symbol',

    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',

    // Managers
    addIncome: 'Add Income',
    incomeSource: 'Income Source',
    amount: 'Amount',
    date: 'Date',
    description: 'Description',
    addExpense: 'Add Expense',
    expenseCategory: 'Expense Category',
    addAsset: 'Add Asset',
    assetName: 'Asset Name',
    assetType: 'Asset Type',
    currentValue: 'Current Value',
    purchasePrice: 'Purchase Price',
    purchaseDate: 'Purchase Date',
    addBankAccount: 'Add Bank Account',
    accountName: 'Account Name',
    accountNumber: 'Account Number',
    bankName: 'Bank Name',
    selectMonth: 'Select Month',
    noData: 'No data available',
    manageYourFinances: 'Manage your finances with ease',
    financeManager: 'Finance Manager',
    addNewIncome: 'Add New Income',
    addNewExpense: 'Add New Expense',
    addNewAsset: 'Add New Asset',
    totalAssetsCount: 'Total Assets',
    totalAssetsLabel: '{count} assets',

    // Analytics
    assetDistribution: 'Asset Distribution',
    portfolioAllocation: 'Your portfolio allocation',
    incomeVsExpenses: 'Income vs Expenses',
    sixMonthTrend: '6-month trend comparison',
    topSpendingCategories: 'Top Spending Categories',
    highestExpenseCategories: 'Your highest expense categories',
    assetPerformance: 'Asset Performance',
    gainsAndLosses: 'Gains and losses on your assets',
  },
  es: {
    // Navigation
    dashboard: 'Panel de Control',
    income: 'Ingresos',
    expenses: 'Gastos',
    assets: 'Activos',
    bankAccounts: 'Cuentas Bancarias',
    budget: 'Presupuesto',
    analytics: 'Analítica',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',

    // Dashboard
    netWorth: 'Patrimonio Neto',
    totalIncome: 'Ingresos Totales',
    monthlyExpenses: 'Gastos Mensuales',
    totalAssets: 'Activos Totales',
    allTimeIncome: 'Ingresos de todos los tiempos',
    thisMonth: 'Este mes',

    // Auth
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    name: 'Nombre',
    invalidEmail: 'Formato de correo inválido',
    passwordRequired: 'Se requiere contraseña',
    failedToLogin: 'Error al iniciar sesión',
    failedToSignup: 'Error al registrarse',

    // Settings
    currentCurrency: 'Moneda Actual',
    selectCurrency: 'Seleccionar Moneda',
    currencyBadges: 'Insignias de Moneda',
    allCurrencies: 'Todas las Monedas Disponibles',
    currencyStatistics: 'Estadísticas de Moneda',
    totalCurrencies: 'Monedas Totales',
    currentLanguage: 'Idioma Actual',
    selectLanguage: 'Seleccionar Idioma',
    yourActiveLanguage: 'Tu configuración de idioma activo',
    allLanguages: 'Todos los Idiomas Admitidos',
    languageStatistics: 'Estadísticas de Idioma',
    totalLanguages: 'Idiomas Totales',
    symbol: 'Símbolo',

    // Common
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    close: 'Cerrar',

    // Managers
    addIncome: 'Agregar Ingresos',
    incomeSource: 'Fuente de Ingresos',
    amount: 'Cantidad',
    date: 'Fecha',
    description: 'Descripción',
    addExpense: 'Agregar Gasto',
    expenseCategory: 'Categoría de Gasto',
    addAsset: 'Agregar Activo',
    assetName: 'Nombre del Activo',
    assetType: 'Tipo de Activo',
    currentValue: 'Valor Actual',
    purchasePrice: 'Precio de Compra',
    purchaseDate: 'Fecha de Compra',
    addBankAccount: 'Agregar Cuenta Bancaria',
    accountName: 'Nombre de la Cuenta',
    accountNumber: 'Número de Cuenta',
    bankName: 'Nombre del Banco',
    selectMonth: 'Seleccionar Mes',
    noData: 'Sin datos disponibles',
    manageYourFinances: 'Gestiona tus finanzas con facilidad',
    financeManager: 'Gestor de Finanzas',
    addNewIncome: 'Agregar Nuevo Ingreso',
    addNewExpense: 'Agregar Nuevo Gasto',
    addNewAsset: 'Agregar Nuevo Activo',
    totalAssetsCount: 'Activos Totales',
    totalAssetsLabel: '{count} activos',

    // Analytics
    assetDistribution: 'Distribución de Activos',
    portfolioAllocation: 'Su asignación de cartera',
    incomeVsExpenses: 'Ingresos vs Gastos',
    sixMonthTrend: 'Comparación de tendencia de 6 meses',
    topSpendingCategories: 'Categorías de Gasto Superior',
    highestExpenseCategories: 'Sus categorías de gasto más altas',
    assetPerformance: 'Rendimiento de Activos',
    gainsAndLosses: 'Ganancias y pérdidas en sus activos',
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de Bord',
    income: 'Revenus',
    expenses: 'Dépenses',
    assets: 'Actifs',
    bankAccounts: 'Comptes Bancaires',
    budget: 'Budget',
    analytics: 'Analytique',
    settings: 'Paramètres',
    logout: 'Déconnexion',

    // Dashboard
    netWorth: 'Valeur Nette',
    totalIncome: 'Revenu Total',
    monthlyExpenses: 'Dépenses Mensuelles',
    totalAssets: 'Actifs Totaux',
    allTimeIncome: 'Revenu de tous les temps',
    thisMonth: 'Ce mois',

    // Auth
    login: 'Connexion',
    signup: 'Inscription',
    email: 'Email',
    password: 'Mot de passe',
    name: 'Nom',
    invalidEmail: 'Format d\'email invalide',
    passwordRequired: 'Le mot de passe est requis',
    failedToLogin: 'Échec de la connexion',
    failedToSignup: 'Échec de l\'inscription',

    // Settings
    currentCurrency: 'Devise Actuelle',
    selectCurrency: 'Sélectionner une Devise',
    currencyBadges: 'Badges de Devise',
    allCurrencies: 'Toutes les Devises Disponibles',
    currencyStatistics: 'Statistiques de Devise',
    totalCurrencies: 'Total des Devises',
    currentLanguage: 'Langue Actuelle',
    selectLanguage: 'Sélectionner une Langue',
    yourActiveLanguage: 'Vos paramètres de langue active',
    allLanguages: 'Toutes les Langues Supportées',
    languageStatistics: 'Statistiques de Langue',
    totalLanguages: 'Total des Langues',
    symbol: 'Symbole',

    // Common
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    close: 'Fermer',

    // Managers
    addIncome: 'Ajouter un Revenu',
    incomeSource: 'Source de Revenu',
    amount: 'Montant',
    date: 'Date',
    description: 'Description',
    addExpense: 'Ajouter une Dépense',
    expenseCategory: 'Catégorie de Dépense',
    addAsset: 'Ajouter un Actif',
    assetName: 'Nom de l\'Actif',
    assetType: 'Type d\'Actif',
    currentValue: 'Valeur Actuelle',
    purchasePrice: 'Prix d\'Achat',
    purchaseDate: 'Date d\'Achat',
    addBankAccount: 'Ajouter un Compte Bancaire',
    accountName: 'Nom du Compte',
    accountNumber: 'Numéro de Compte',
    bankName: 'Nom de la Banque',
    selectMonth: 'Sélectionner un Mois',
    noData: 'Aucune donnée disponible',
    manageYourFinances: 'Gérez vos finances facilement',
    financeManager: 'Gestionnaire Financier',
    addNewIncome: 'Ajouter un Nouveau Revenu',
    addNewExpense: 'Ajouter une Nouvelle Dépense',
    addNewAsset: 'Ajouter un Nouvel Actif',
    totalAssetsCount: 'Actifs Totaux',
    totalAssetsLabel: '{count} actifs',

    // Analytics
    assetDistribution: 'Distribution des Actifs',
    portfolioAllocation: 'Votre allocation de portefeuille',
    incomeVsExpenses: 'Revenus vs Dépenses',
    sixMonthTrend: 'Comparaison de tendance sur 6 mois',
    topSpendingCategories: 'Catégories de Dépenses Principales',
    highestExpenseCategories: 'Vos catégories de dépenses les plus élevées',
    assetPerformance: 'Performance des Actifs',
    gainsAndLosses: 'Gains et pertes sur vos actifs',
  },
  de: {
    // Navigation
    dashboard: 'Armaturenbrett',
    income: 'Einkommen',
    expenses: 'Ausgaben',
    assets: 'Vermögenswerte',
    bankAccounts: 'Bankkonten',
    budget: 'Budget',
    analytics: 'Analytik',
    settings: 'Einstellungen',
    logout: 'Abmelden',

    // Dashboard
    netWorth: 'Vermögen',
    totalIncome: 'Gesamteinkommen',
    monthlyExpenses: 'Monatliche Ausgaben',
    totalAssets: 'Gesamtvermögen',
    allTimeIncome: 'Einkommen aller Zeiten',
    thisMonth: 'Diesen Monat',

    // Auth
    login: 'Anmelden',
    signup: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    name: 'Name',
    invalidEmail: 'Ungültiges E-Mail-Format',
    passwordRequired: 'Passwort erforderlich',
    failedToLogin: 'Anmeldung fehlgeschlagen',
    failedToSignup: 'Registrierung fehlgeschlagen',

    // Settings
    currentCurrency: 'Aktuelle Währung',
    selectCurrency: 'Währung Wählen',
    currencyBadges: 'Währungsabzeichen',
    allCurrencies: 'Alle verfügbaren Währungen',
    currencyStatistics: 'Währungsstatistiken',
    totalCurrencies: 'Gesamtwährungen',
    currentLanguage: 'Aktuelle Sprache',
    selectLanguage: 'Sprache Wählen',
    yourActiveLanguage: 'Ihre aktiven Spracheinstellungen',
    allLanguages: 'Alle unterstützten Sprachen',
    languageStatistics: 'Sprachstatistiken',
    totalLanguages: 'Gesamtsprachen',
    symbol: 'Symbol',

    // Common
    loading: 'Wird geladen...',
    error: 'Fehler',
    success: 'Erfolg',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    add: 'Hinzufügen',
    close: 'Schließen',

    // Managers
    addIncome: 'Einkommen Hinzufügen',
    incomeSource: 'Einkommensquelle',
    amount: 'Betrag',
    date: 'Datum',
    description: 'Beschreibung',
    addExpense: 'Ausgabe Hinzufügen',
    expenseCategory: 'Ausgabenkategorie',
    addAsset: 'Vermögenswert Hinzufügen',
    assetName: 'Name des Vermögenswertes',
    assetType: 'Art des Vermögenswertes',
    currentValue: 'Aktueller Wert',
    purchasePrice: 'Kaufpreis',
    purchaseDate: 'Kaufdatum',
    addBankAccount: 'Bankkonto Hinzufügen',
    accountName: 'Kontoname',
    accountNumber: 'Kontonummer',
    bankName: 'Bankname',
    selectMonth: 'Monat Wählen',
    noData: 'Keine Daten verfügbar',
    manageYourFinances: 'Verwalten Sie Ihre Finanzen einfach',
    financeManager: 'Finanzmanager',
    addNewIncome: 'Neues Einkommen Hinzufügen',
    addNewExpense: 'Neue Ausgabe Hinzufügen',
    addNewAsset: 'Neuen Vermögenswert Hinzufügen',
    totalAssetsCount: 'Gesamtvermögen',
    totalAssetsLabel: '{count} Vermögenswerte',

    // Analytics
    assetDistribution: 'Vermögensverteilung',
    portfolioAllocation: 'Ihre Portfolio-Allokation',
    incomeVsExpenses: 'Einnahmen vs. Ausgaben',
    sixMonthTrend: '6-Monats-Trendvergleich',
    topSpendingCategories: 'Top-Ausgabenkategorien',
    highestExpenseCategories: 'Ihre höchsten Ausgabenkategorien',
    assetPerformance: 'Vermögensperformance',
    gainsAndLosses: 'Gewinne und Verluste aus Ihren Vermögenswerten',
  },
  zh: {
    // Navigation
    dashboard: '仪表盘',
    income: '收入',
    expenses: '支出',
    assets: '资产',
    bankAccounts: '银行账户',
    budget: '预算',
    analytics: '分析',
    settings: '设置',
    logout: '登出',

    // Dashboard
    netWorth: '净资产',
    totalIncome: '总收入',
    monthlyExpenses: '月度支出',
    totalAssets: '总资产',
    allTimeIncome: '历史总收入',
    thisMonth: '本月',

    // Auth
    login: '登录',
    signup: '注册',
    email: '邮箱',
    password: '密码',
    name: '名称',
    invalidEmail: '无效的邮箱格式',
    passwordRequired: '密码必需',
    failedToLogin: '登录失败',
    failedToSignup: '注册失败',

    // Settings
    currentCurrency: '当前货币',
    selectCurrency: '选择货币',
    currencyBadges: '货币徽章',
    allCurrencies: '所有可用货币',
    currencyStatistics: '货币统计',
    totalCurrencies: '总货币数',
    currentLanguage: '当前语言',
    selectLanguage: '选择语言',
    yourActiveLanguage: '您的活跃语言设置',
    allLanguages: '所有支持的语言',
    languageStatistics: '语言统计',
    totalLanguages: '总语言数',
    symbol: '符号',

    // Common
    loading: '加载中...',
    error: '错误',
    success: '成功',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    add: '添加',
    close: '关闭',

    // Managers
    addIncome: '添加收入',
    incomeSource: '收入来源',
    amount: '金额',
    date: '日期',
    description: '描述',
    addExpense: '添加支出',
    expenseCategory: '支出类别',
    addAsset: '添加资产',
    assetName: '资产名称',
    assetType: '资产类型',
    currentValue: '当前价值',
    purchasePrice: '购买价格',
    purchaseDate: '购买日期',
    addBankAccount: '添加银行账户',
    accountName: '账户名称',
    accountNumber: '账户号码',
    bankName: '银行名称',
    selectMonth: '选择月份',
    noData: '无数据可用',
    manageYourFinances: '轻松管理您的财务',
    financeManager: '财务管理器',
    addNewIncome: '添加新收入',
    addNewExpense: '添加新支出',
    addNewAsset: '添加新资产',
    totalAssetsCount: '总资产',
    totalAssetsLabel: '{count}资产',
    // Analytics
    assetDistribution: '资产分配',
    portfolioAllocation: '您的投资组合配置',
    incomeVsExpenses: '收入与支出',
    sixMonthTrend: '6个月趋势比较',
    topSpendingCategories: '最高支出类别',
    highestExpenseCategories: '您最高的支出类别',
    assetPerformance: '资产表现',
    gainsAndLosses: '您资产的收益和损失',  },
  ja: {
    // Navigation
    dashboard: 'ダッシュボード',
    income: '収入',
    expenses: '支出',
    assets: '資産',
    bankAccounts: '銀行口座',
    budget: '予算',
    analytics: '分析',
    settings: '設定',
    logout: 'ログアウト',

    // Dashboard
    netWorth: '正味資産',
    totalIncome: '総収入',
    monthlyExpenses: '月間支出',
    totalAssets: '総資産',
    allTimeIncome: 'これまでの収入',
    thisMonth: '今月',

    // Auth
    login: 'ログイン',
    signup: 'サインアップ',
    email: 'メール',
    password: 'パスワード',
    name: '名前',
    invalidEmail: '無効なメール形式',
    passwordRequired: 'パスワードが必要です',
    failedToLogin: 'ログインに失敗しました',
    failedToSignup: 'サインアップに失敗しました',

    // Settings
    currentCurrency: '現在の通貨',
    selectCurrency: '通貨を選択',
    currencyBadges: '通貨バッジ',
    allCurrencies: 'すべての利用可能な通貨',
    currencyStatistics: '通貨統計',
    totalCurrencies: '通貨総数',
    currentLanguage: '現在の言語',
    selectLanguage: '言語を選択',
    yourActiveLanguage: 'アクティブな言語設定',
    allLanguages: 'サポートされているすべての言語',
    languageStatistics: '言語統計',
    totalLanguages: '言語総数',
    symbol: 'シンボル',

    // Common
    loading: '読み込み中...',
    error: 'エラー',
    success: '成功',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    add: '追加',
    close: '閉じる',

    // Managers
    addIncome: '収入を追加',
    incomeSource: '収入源',
    amount: '金額',
    date: '日付',
    description: '説明',
    addExpense: '支出を追加',
    expenseCategory: '支出カテゴリ',
    addAsset: '資産を追加',
    assetName: '資産名',
    assetType: '資産タイプ',
    currentValue: '現在価値',
    purchasePrice: '購入価格',
    purchaseDate: '購入日',
    addBankAccount: '銀行口座を追加',
    accountName: 'アカウント名',
    accountNumber: 'アカウント番号',
    bankName: '銀行名',
    selectMonth: '月を選択',
    noData: 'データなし',
    manageYourFinances: 'あなたの財務を簡単に管理する',
    financeManager: 'ファイナンシャルマネージャー',
    addNewIncome: '新しい収入を追加',
    addNewExpense: '新しい支出を追加',
    addNewAsset: '新しい資産を追加',
    totalAssetsCount: '総資産',
    totalAssetsLabel: '{count}資産',
    // Analytics
    assetDistribution: '資産分配',
    portfolioAllocation: 'ポートフォリオの配分',
    incomeVsExpenses: '収入対支出',
    sixMonthTrend: '6ヶ月のトレンド比較',
    topSpendingCategories: 'トップ支出カテゴリー',
    highestExpenseCategories: '最高の支出カテゴリー',
    assetPerformance: '資産パフォーマンス',
    gainsAndLosses: '資産の利益と損失',  },
  hi: {
    // Navigation
    dashboard: 'डैशबोर्ड',
    income: 'आय',
    expenses: 'खर्च',
    assets: 'संपत्ति',
    bankAccounts: 'बैंक खाते',
    budget: 'बजट',
    analytics: 'विश्लेषण',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',

    // Dashboard
    netWorth: 'शुद्ध संपत्ति',
    totalIncome: 'कुल आय',
    monthlyExpenses: 'मासिक खर्च',
    totalAssets: 'कुल संपत्ति',
    allTimeIncome: 'सभी समय की आय',
    thisMonth: 'इस महीने',

    // Auth
    login: 'लॉगिन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    invalidEmail: 'अमान्य ईमेल प्रारूप',
    passwordRequired: 'पासवर्ड आवश्यक है',
    failedToLogin: 'लॉगिन विफल',
    failedToSignup: 'साइन अप विफल',

    // Settings
    currentCurrency: 'वर्तमान मुद्रा',
    selectCurrency: 'मुद्रा चुनें',
    currencyBadges: 'मुद्रा बैज',
    allCurrencies: 'सभी उपलब्ध मुद्राएं',
    currencyStatistics: 'मुद्रा आंकड़े',
    totalCurrencies: 'कुल मुद्राएं',
    currentLanguage: 'वर्तमान भाषा',
    selectLanguage: 'भाषा चुनें',
    yourActiveLanguage: 'आपकी सक्रिय भाषा सेटिंग्स',
    allLanguages: 'सभी समर्थित भाषाएं',
    languageStatistics: 'भाषा आंकड़े',
    totalLanguages: 'कुल भाषाएं',
    symbol: 'चिन्ह',

    // Common
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    close: 'बंद करें',

    // Managers
    addIncome: 'आय जोड़ें',
    incomeSource: 'आय का स्रोत',
    amount: 'राशि',
    date: 'तारीख',
    description: 'विवरण',
    addExpense: 'व्यय जोड़ें',
    expenseCategory: 'व्यय श्रेणी',
    addAsset: 'संपत्ति जोड़ें',
    assetName: 'संपत्ति का नाम',
    assetType: 'संपत्ति का प्रकार',
    currentValue: 'वर्तमान मूल्य',
    purchasePrice: 'क्रय मूल्य',
    purchaseDate: 'क्रय तारीख',
    addBankAccount: 'बैंक खाता जोड़ें',
    accountName: 'खाते का नाम',
    accountNumber: 'खाता संख्या',
    bankName: 'बैंक का नाम',
    selectMonth: 'महीना चुनें',
    noData: 'कोई डेटा उपलब्ध नहीं',
    manageYourFinances: 'अपने वित्त को आसानी से प्रबंधित करें',
    financeManager: 'वित्तीय प्रबंधक',
    addNewIncome: 'नई आय जोड़ें',
    addNewExpense: 'नया व्यय जोड़ें',
    addNewAsset: 'नई संपत्ति जोड़ें',
    totalAssetsCount: 'कुल संपत्ति',
    totalAssetsLabel: '{count} संपत्ति',
    // Analytics
    assetDistribution: 'संपत्ति वितरण',
    portfolioAllocation: 'आपका पोर्टफोलियो आवंटन',
    incomeVsExpenses: 'आय बनाम व्यय',
    sixMonthTrend: '6 महीने की प्रवृत्ति तुलना',
    topSpendingCategories: 'शीर्ष व्यय श्रेणियां',
    highestExpenseCategories: 'आपकी उच्चतम व्यय श्रेणियां',
    assetPerformance: 'संपत्ति प्रदर्शन',
    gainsAndLosses: 'आपकी संपत्ति पर लाभ और हानि',  },
  pt: {
    // Navigation
    dashboard: 'Painel de Controle',
    income: 'Renda',
    expenses: 'Despesas',
    assets: 'Ativos',
    bankAccounts: 'Contas Bancárias',
    budget: 'Orçamento',
    analytics: 'Análise',
    settings: 'Configurações',
    logout: 'Sair',

    // Dashboard
    netWorth: 'Patrimônio Líquido',
    totalIncome: 'Renda Total',
    monthlyExpenses: 'Despesas Mensais',
    totalAssets: 'Ativos Totais',
    allTimeIncome: 'Renda de todos os tempos',
    thisMonth: 'Este mês',

    // Auth
    login: 'Entrar',
    signup: 'Criar Conta',
    email: 'Email',
    password: 'Senha',
    name: 'Nome',
    invalidEmail: 'Formato de email inválido',
    passwordRequired: 'Senha é obrigatória',
    failedToLogin: 'Falha ao entrar',
    failedToSignup: 'Falha ao criar conta',

    // Settings
    currentCurrency: 'Moeda Atual',
    selectCurrency: 'Selecionar Moeda',
    currencyBadges: 'Crachás de Moeda',
    allCurrencies: 'Todas as Moedas Disponíveis',
    currencyStatistics: 'Estatísticas de Moeda',
    totalCurrencies: 'Total de Moedas',
    currentLanguage: 'Idioma Atual',
    selectLanguage: 'Selecionar Idioma',
    yourActiveLanguage: 'Suas configurações de idioma ativo',
    allLanguages: 'Todos os Idiomas Suportados',
    languageStatistics: 'Estatísticas de Idioma',
    totalLanguages: 'Total de Idiomas',
    symbol: 'Símbolo',

    // Common
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    add: 'Adicionar',
    close: 'Fechar',

    // Managers
    addIncome: 'Adicionar Renda',
    incomeSource: 'Fonte de Renda',
    amount: 'Valor',
    date: 'Data',
    description: 'Descrição',
    addExpense: 'Adicionar Despesa',
    expenseCategory: 'Categoria de Despesa',
    addAsset: 'Adicionar Ativo',
    assetName: 'Nome do Ativo',
    assetType: 'Tipo de Ativo',
    currentValue: 'Valor Atual',
    purchasePrice: 'Preço de Compra',
    purchaseDate: 'Data de Compra',
    addBankAccount: 'Adicionar Conta Bancária',
    accountName: 'Nome da Conta',
    accountNumber: 'Número da Conta',
    bankName: 'Nome do Banco',
    selectMonth: 'Selecionar Mês',
    noData: 'Nenhum dado disponível',
    manageYourFinances: 'Gerencie suas finanças com facilidade',
    financeManager: 'Gerenciador de Finanças',
    addNewIncome: 'Adicionar Nova Renda',
    addNewExpense: 'Adicionar Nova Despesa',
    addNewAsset: 'Adicionar Novo Ativo',
    totalAssetsCount: 'Ativos Totais',
    totalAssetsLabel: '{count} ativos',
    // Analytics
    assetDistribution: 'Distribuição de Ativos',
    portfolioAllocation: 'Sua alocação de portfólio',
    incomeVsExpenses: 'Renda vs Despesas',
    sixMonthTrend: 'Comparação de tendência de 6 meses',
    topSpendingCategories: 'Principais Categorias de Gasto',
    highestExpenseCategories: 'Suas categorias de despesa mais altas',
    assetPerformance: 'Desempenho de Ativos',
    gainsAndLosses: 'Ganhos e perdas em seus ativos',  },
  ru: {
    // Navigation
    dashboard: 'Приборная панель',
    income: 'Доход',
    expenses: 'Расходы',
    assets: 'Активы',
    bankAccounts: 'Банковские счета',
    budget: 'Бюджет',
    analytics: 'Аналитика',
    settings: 'Настройки',
    logout: 'Выход',

    // Dashboard
    netWorth: 'Чистое состояние',
    totalIncome: 'Общий доход',
    monthlyExpenses: 'Месячные расходы',
    totalAssets: 'Общие активы',
    allTimeIncome: 'Доход за все время',
    thisMonth: 'В этом месяце',

    // Auth
    login: 'Вход',
    signup: 'Регистрация',
    email: 'Электронная почта',
    password: 'Пароль',
    name: 'Имя',
    invalidEmail: 'Неверный формат электронной почты',
    passwordRequired: 'Пароль обязателен',
    failedToLogin: 'Ошибка входа',
    failedToSignup: 'Ошибка регистрации',

    // Settings
    currentCurrency: 'Текущая валюта',
    selectCurrency: 'Выбрать валюту',
    currencyBadges: 'Значки валют',
    allCurrencies: 'Все доступные валюты',
    currencyStatistics: 'Статистика валют',
    totalCurrencies: 'Всего валют',
    currentLanguage: 'Текущий язык',
    selectLanguage: 'Выбрать язык',
    yourActiveLanguage: 'Ваши активные языковые настройки',
    allLanguages: 'Все поддерживаемые языки',
    languageStatistics: 'Статистика языков',
    totalLanguages: 'Всего языков',
    symbol: 'Символ',

    // Common
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успех',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    add: 'Добавить',
    close: 'Закрыть',

    // Managers
    addIncome: 'Добавить доход',
    incomeSource: 'Источник дохода',
    amount: 'Сумма',
    date: 'Дата',
    description: 'Описание',
    addExpense: 'Добавить расход',
    expenseCategory: 'Категория расходов',
    addAsset: 'Добавить актив',
    assetName: 'Название актива',
    assetType: 'Тип актива',
    currentValue: 'Текущая стоимость',
    purchasePrice: 'Цена покупки',
    purchaseDate: 'Дата покупки',
    addBankAccount: 'Добавить банковский счет',
    accountName: 'Имя учетной записи',
    accountNumber: 'Номер счета',
    bankName: 'Название банка',
    selectMonth: 'Выбрать месяц',
    noData: 'Данные недоступны',
    manageYourFinances: 'Управляйте своими финансами с легкостью',
    financeManager: 'Финансовый менеджер',
    addNewIncome: 'Добавить новый доход',
    addNewExpense: 'Добавить новый расход',
    addNewAsset: 'Добавить новый актив',
    totalAssetsCount: 'Всего активов',
    totalAssetsLabel: '{count} активов',
    // Analytics
    assetDistribution: 'Распределение активов',
    portfolioAllocation: 'Ваше распределение портфеля',
    incomeVsExpenses: 'Доход vs Расходы',
    sixMonthTrend: 'Сравнение тенденций за 6 месяцев',
    topSpendingCategories: 'Топ категории расходов',
    highestExpenseCategories: 'Ваши наивысшие категории расходов',
    assetPerformance: 'Производительность активов',
    gainsAndLosses: 'Прибыль и убыток по вашим активам',  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    income: 'الدخل',
    expenses: 'المصروفات',
    assets: 'الأصول',
    bankAccounts: 'حسابات البنك',
    budget: 'الموازنة',
    analytics: 'التحليلات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',

    // Dashboard
    netWorth: 'صافي الثروة',
    totalIncome: 'إجمالي الدخل',
    monthlyExpenses: 'نفقات شهرية',
    totalAssets: 'إجمالي الأصول',
    allTimeIncome: 'الدخل طوال الوقت',
    thisMonth: 'هذا الشهر',

    // Auth
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم',
    invalidEmail: 'صيغة بريد إلكتروني غير صالحة',
    passwordRequired: 'كلمة المرور مطلوبة',
    failedToLogin: 'فشل تسجيل الدخول',
    failedToSignup: 'فشل إنشاء الحساب',

    // Settings
    currentCurrency: 'العملة الحالية',
    selectCurrency: 'اختر عملة',
    currencyBadges: 'شارات العملة',
    allCurrencies: 'جميع العملات المتاحة',
    currencyStatistics: 'إحصائيات العملة',
    totalCurrencies: 'إجمالي العملات',
    currentLanguage: 'اللغة الحالية',
    selectLanguage: 'اختر لغة',
    yourActiveLanguage: 'إعدادات اللغة النشطة لديك',
    allLanguages: 'جميع اللغات المدعومة',
    languageStatistics: 'إحصائيات اللغة',
    totalLanguages: 'إجمالي اللغات',
    symbol: 'رمز',

    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تحرير',
    add: 'إضافة',
    close: 'إغلاق',

    // Managers
    addIncome: 'إضافة دخل',
    incomeSource: 'مصدر الدخل',
    amount: 'المبلغ',
    date: 'التاريخ',
    description: 'الوصف',
    addExpense: 'إضافة نفقة',
    expenseCategory: 'فئة النفقات',
    addAsset: 'إضافة أصل',
    assetName: 'اسم الأصل',
    assetType: 'نوع الأصل',
    currentValue: 'القيمة الحالية',
    purchasePrice: 'سعر الشراء',
    purchaseDate: 'تاريخ الشراء',
    addBankAccount: 'إضافة حساب بنكي',
    accountName: 'اسم الحساب',
    accountNumber: 'رقم الحساب',
    bankName: 'اسم البنك',
    selectMonth: 'اختر شهر',
    noData: 'لا توجد بيانات متاحة',
    manageYourFinances: 'إدارة أموالك بسهولة',
    financeManager: 'مدير المالية',
    addNewIncome: 'إضافة دخل جديد',
    addNewExpense: 'إضافة نفقة جديدة',
    addNewAsset: 'إضافة أصل جديد',
    totalAssetsCount: 'إجمالي الأصول',
    totalAssetsLabel: '{count}الأصول',
    // Analytics
    assetDistribution: 'توزيع الأصول',
    portfolioAllocation: 'تخصيص المحفظة الخاصة بك',
    incomeVsExpenses: 'الدخل مقابل النفقات',
    sixMonthTrend: 'مقارنة الاتجاه لمدة 6 أشهر',
    topSpendingCategories: 'فئات الإنفاق الأعلى',
    highestExpenseCategories: 'فئات النفقات الأعلى لديك',
    assetPerformance: 'أداء الأصول',
    gainsAndLosses: 'الأرباح والخسائر على أصولك',  },
};

export function getLanguageName(code: LanguageCode): string {
  const lang = SUPPORTED_LANGUAGES.find(l => l.code === code);
  return lang?.nativeName || code;
}

export function getLanguageDetails(code: LanguageCode) {
  return SUPPORTED_LANGUAGES.find(l => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export function getCurrentLanguageCode(): LanguageCode {
  if (typeof window !== 'undefined') {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved && translations[saved]) {
      return saved as LanguageCode;
    }
  }
  return DEFAULT_LANGUAGE as LanguageCode;
}

export function getTranslation(key: string, languageCode?: LanguageCode): string {
  const code = languageCode || getCurrentLanguageCode();
  return translations[code]?.[key] || translations[DEFAULT_LANGUAGE][key] || key;
}
